rules:
  - name: Changed runtime files
    condition: .*/runtime/.*lib.rs
    check_type: changed_files
    min_approvals: 2
    teams:
      - polkadotleads

  - name: Substrate developers
    check_type: changed_files
    condition: .*
    min_approvals: 2
    teams:
      - core-devs
